name: Generate and retrieve CSV

on:
  push:
    branches:
      - master

jobs:
  generate-csv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17]
    inputs:
      csv-filename:
        description: 'Name of the CSV file to generate'
        required: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.10.10' # Replace with the version of Python you want to use
    - name: Install dependencies
      run: pip install pandas # Replace with the name of your requirements file, if you have one
    - name: Generate CSV
      run: python ·/src/ck.py --filename ${{ inputs.CSV_FILENAME }}
    - name: Upload CSV artifact
      uses: actions/upload-artifact@v2
      with:
        name: generated-csv
        path: ./src/data/repos.csv # Replace with the path to your generated CSV file

